server {
  listen 8080;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;
  gzip on;
  gzip_comp_level 6;
  gzip_types *;
  gzip_vary on;
  etag on;
  if_modified_since before;
  location / {
    try_files $uri $uri/ /index.html;
  }
}
